### ISSUE TITLE
Node modules

### ISSUE THREAD

**Issue by discordbotengineering** [ZerioDev/Music-bot#295]
Can you pls update package.json file? I guess this error about ytdl-core

error: 

ERR_NO_RESULT: Could not extract stream for this track

evalmachine.<anonymous>:426
koa=function(a,b,c,d){var e=null;switch(b){case "JSON":try{var f=c.responseText}catch(h){throw d=Error("Error reading responseText"),d.params=a,JB(d),h;}a=c.getResponseHeader("Content-Type")||"";f&&0<=a.indexOf("json")&&(")]};gma(ncode);

**Comment by Nickeldon** [comment]
Sadly, this error is due to current issues in the latest version of the ytdl-core module. Feel free to visit our Discord Issues threads to follow one of our team members' tutorials to fix this issue.

[If you are already part of our discord server]:

Fix one (Downgrading): https://discord.com/channels/773639842449850368/1149985204400824403

Fix two (Direct modification of the package source code): https://discord.com/channels/773639842449850368/1150095560200687690

Feel free to ask if you have any concerns.

**Comment by discordbotengineering** [comment]
If  can be ytdlcore version 4.9.1 the bot is working. So can you update package.json  with modules's old version. the bot will work.

**Comment by Nickeldon** [comment]
> If can be ytdlcore version 4.9.1 the bot is working. So can you update package.json with modules's old version. the bot will

I know... Nevertheless, be aware that using a deprecated version of ytdl-core will slow down your streaming speed.

**Comment by discordbotengineering** [comment]
then must we wait ytdl-core fix the problem?
